# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: my-agent

steps:
- task: TerraformInstaller@1
  displayName: Terraform install
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'my-service-connection'
    backendAzureRmOverrideSubscriptionID: '8e31d1d4-7aa9-4b0a-9687-fdca97e1bd8c'
    backendAzureRmResourceGroupName: 'rg'
    backendAzureRmStorageAccountName: 'woolenstorage'
    backendAzureRmContainerName: 'woolen-container'
    backendAzureRmKey: 'woolen-statefile'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'